version: '3.8'

services:
    selenium-server:
        # ref: https://github.com/SeleniumHQ/docker-selenium
        image: selenium/standalone-chrome:4.0.0-rc-1-prerelease-20210618
        ports:
            - "4444:4444"
        volumes:
            - /dev/shm:/dev/shm
        networks:
            selenium-instance:    

    selenium-proxy-server:
        build: .
        ports:
            - "8080:8080"
        depends_on:
            - selenium-server
        networks:
            selenium-instance:
    

networks:
    selenium-instance:
